### ISSUE TITLE
Feedback from project sponsor

### ISSUE THREAD

**Issue by anbo-de** [Perevalov/nuance-core#16]
# Context 

I had a talk with the project sponsor and collected his feedback and his demands after checking the currently deployed application as well as looking at the source code.

# Definition of Done

 * [x]  The first output of the chatbot was changed to "What information do you need?".
 * [x]  The frontend was extended to provided examples (and example dialogs) and a description of available patterns.
   * the underlying goal is to help users getting familiar with the application
   * suggestion: add a new menu item where a page is linked containing the required information
 * [x] All Qanary components are documented.
   * the documentation should contain:
     * the intention of the component
     * a description of the required data types (input)
     * a description of the produced data types (output)
     * a typical use within a QA pipeline (what components should have been executed before/after this component)
     * libraries/approaches used for the implementation
   * options:
     * write the documentation of the components in the component's main Python file (start of the file)
     * write an additional Markdown file as documentation in the same folder as the component's main Python file

**Comment by Perevalov** [comment]
Done
